version: "3.9"

services:
  web:
    build:
      context: .
    image: ai_image_ads:dev
    container_name: ai_image_ads_web
    command: bin/rails server -b 0.0.0.0 -p 3000
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .:/rails:cached
      - bundle:/usr/local/bundle
      - node_modules:/rails/node_modules
    depends_on:
      - mongo
    stdin_open: true
    tty: true

  mongo:
    image: mongo:7
    container_name: mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
  bundle:
  node_modules:
